# Generated by Django 3.1.1 on 2020-09-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow_engine', '0002_fileupload_calculated_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='calculated_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
