# Generated by Django 3.1.1 on 2020-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow_engine', '0003_auto_20200912_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filetxt',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
